### ISSUE TITLE
Problem starting MenuTools on 64bit OS

### ISSUE THREAD

**Issue by Big--Mike** [navossoc/MenuTools#1]
Hi,

I've got a problem starting MenuTools on my 64bit Windows 10. There's no problem on a 32bit Windows 10.
It seems, that there's a problem, when MenuTools.exe tries to launch MenuTools64.exe if you're not in the MenuTools install folder. 
As MenuTools requires admin rights, I've created a scheduled task running 
c:\program files\menutools\menutools.exe
with highest priviledges to circumvent UAC. This doesn't work. The process exits silently.
Adding the working directory doesn't work either.

But - as a workaround - launching
cmd /c start /d "c:\program files\menutools" /b menutools.exe
works fine.

**Comment by navossoc** [comment]
I never realized that! Really weird stuff ;)

I'll check it later today.

Thanks!

**Comment by navossoc** [comment]
To be honest, I did a few quick tests here...
The startup behavior is wrong in every Windows I have tested (7 x86, 8 x86, 8.1 x86 and 10 x86)

Not sure how I missed that... I'll keep looking into it.

**Comment by Big--Mike** [comment]
Actually I didn't "many tests" on a x86 platform. I've installed the program, removed the startup shortcut, created the task to start it with elevated privileges and it worked like a charm. Repeating the procedure on a x64 based Windows 10, I ran into the problem and started testing there.
Maybe the processor architecture isn't the cause.

**Comment by navossoc** [comment]
I found the problem yesterday, if you have the UAC enabled you can't launch a program that requires administrator privileges.
If I remember right, I didn't use UAC back then, so I never realized it.

Creating a task in the scheduler may solve the problem, but as you said it doesn't seems to work on Windows 10 x64, I'm looking why...

**Comment by navossoc** [comment]
Hey mate, I didn't forgot about you...

I'm debating how to redesign the whole thing, including add more features and make it more compatible.

I'll let you know when I have more information.

**Comment by Big--Mike** [comment]
Hey,
nice to hear, that you are planning to add some features. I hope the impact on the resource usage won't be too heavy. One of the fact's, that convinced me, was the very low memory footprint :)
If you plan to add localizations, I could translate the strings to German.

**Comment by Big--Mike** [comment]
Hi, 
since my last comment is older than a year - how is the status? 
Can I help you by testing anything?

**Comment by navossoc** [comment]
Hello @Big--Mike...
To be honest, I ended up putting this idea on hold and never thought too much about it again.

At the moment, I'm doing a plugin for KeePass.
You can check it [here](https://github.com/navossoc/KeePass-Yet-Another-Favicon-Downloader) if you want.

Anyway, I still have some ideas for this program by adding a window manager. Something like [Divvy](http://mizage.com/divvy/) and a few other features (that will help me a lot too).

The only problem I do not know when I would do this.

About this original issue, scheduled tasks are the way to go.
Are you having any new problems or were you just curious if any new projects came up?

**Comment by Big--Mike** [comment]
Actually my problem was, that on a 64bit operating system, I have to run it with the command
"cmd.exe /c start /d "c:\program files\menutools" /b menutools.exe" 
and "c:\program files\menutools\menutools.exe", which works fine on a 32bit operating system doesn't work.
But I have no new problems, and it still works like a charm, once MenuTools is running...
I've never read about Divvy, but it looks interesting.
May I ask, what's wrong with the old FavIcon downloader plugin for KeePass? It works for me...

**Comment by Dainonas** [comment]
Hello :)
I am big fan of manu tools, but long time ago I have switched to "Moo0 Window Menu Plus" - it is also lightwave, and no need to run via task scheduler. It also works not on all windows, for example - it works with google picasa viewer, but does not show up for foxit reader x64. But there are no issues with automatic startup, it also is a simple exe to put somewhere in your "bin" folder.

**Comment by Big--Mike** [comment]
:) I can't see any hints on the Moo0 homepage, that Window Menu Plus supports x64, so this is probably the reason, why it doesn't work with Foxit Reader x64 and MenuTools supports x64, this is a big advantage over many other tools of this category.

**Comment by navossoc** [comment]
@Big--Mike 
Sure the old one still works, but I found him a little bit clumsy...

There a few negative points I see on it:
1. It sometimes can't find the favicon of a few sites.
2. It have a few issues with proxies settings.
3. It runs on a single threaded, so for a large number of entries it takes a good while to complete.

I'm working on that, besides I'm interested in how plugins are made for KeePass.

I think I can do another installer to fix the startup issue.
The only problem with this is: my code signing certificate has expired a long time ago. Because of this, newer versions of Windows will complain a lot to install it, which is not cool at all.

I could try to ask for a [open developer certificate](http://pete.akeo.ie/2011/11/free-code-signing-certificate-for-open.html), but I don't think this project receives too much attention for that.
Just a few people uses it.

So, for now the best way to fix it is create a scheduled task as you said:
`schtasks /create /sc onlogon /TN MenuTools /TR "cmd /c start /d \"%PROGRAMFILES%\MenuTools\" /b MenuTools.exe" /RL HIGHEST /F`

Maybe with the revamp, I could ask for a certificate 😀

**Comment by Big--Mike** [comment]
Ok, I'm using FavIcon Downloader only for single sites, so I never noticed the problems...

MenuTools:
No problem :) As long as it works, I'm fine with it. There's only the ugly cmd window, which pops up for a short time and reminds me, that there's a little start up problem.

**Comment by navossoc** [comment]
@Big--Mike 4 years; 3 months...

But hey, who's counting? 🤣
