### ISSUE TITLE
Doesn't work with programs that have custom system menus

### ISSUE THREAD

**Issue by ghost** [navossoc/MenuTools#12]
Some programs, such as Discord, Chrome, Firefox, Sticky Notes, etc have custom system menus at the top that prevent the usage of this tool. There should be a way to use MenuTools in these applications.

**Comment by fade2gray** [comment]
This works for Win 10 Firefox.

![MenuTools](https://user-images.githubusercontent.com/1332009/144763154-0932e1d5-68f5-4faf-9dca-a45606bee957.png)

**Comment by PseudonymPatel** [comment]
You can also use the shortcut Alt + Space which will bring up this menu. It works on most of these type applications (have not tested chrome), except sticky notes, unfortunately.
